### ISSUE TITLE
作者大大，你好，我opencd训练changer的时候没有问题，但是在测试changer的时候报错（'CDLocalVisualizer is not in the mmengine），还请指点。

### ISSUE THREAD

**Issue by heyujiang1** [likyoo/open-cd#126]
10/12 22:34:30 - mmengine - WARNING - Failed to import `None.registry` make sure the registry.py exists in `None` packag
e.
10/12 22:34:30 - mmengine - WARNING - Failed to search registry with scope "opencd" in the "visualizer" registry tree. A
s a workaround, the current "visualizer" registry in "mmengine" is used to build instance. This may cause unexpected fai
lure when running the built modules. Please check whether "opencd" is a correct scope, or whether the registry is initia
lized.
Traceback (most recent call last):
  File "E:\hyjcode\open-cd-main\tools\test.py", line 114, in <module>
    main()
  File "E:\hyjcode\open-cd-main\tools\test.py", line 107, in main
    runner = Runner.from_cfg(cfg)
  File "E:\Anaconda-File\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 462, in from_cfg
    runner = cls(
  File "E:\Anaconda-File\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 416, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "E:\Anaconda-File\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 803, in build_visualizer       
    return VISUALIZERS.build(visualizer)
  File "E:\Anaconda-File\envs\pytorch\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "E:\Anaconda-File\envs\pytorch\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_c
fg
    raise KeyError(
KeyError: 'CDLocalVisualizer is not in the mmengine::visualizer registry. Please check whether the value of `CDLocalVisu
alizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/lat
est/advanced_tutorials/config.html#import-the-custom-module'
作者大大，你好，我opencd训练changer的时候没有问题，但是在测试changer的时候报错，还请指点。

**Comment by ULTA-Web** [comment]
same problem

**Comment by abdulmajeedali** [comment]
I used opencd as scope and it worked. you need to include the following into your test/train:
# Get the absolute path of the parent folder
parent_dir = '/BUILDING_DETECTION/RSBuilding'

# Add the parent folder ro the system path
sys.path.append(parent_dir)

# Now you can import modules from the parent folder 
from opencd import 

you can refer to the installation guidance at:
[https://github.com/Meize0729/RSBuilding/issues/7](url)
