### ISSUE TITLE
Problems in training stage

### ISSUE THREAD

**Issue by AgustinNormand** [likyoo/open-cd#18]
Hello,
I'm trying to train the model, and I'm having some errors.
I listed each of the tests I ran, the commands that were run on each one, and the output from these.
I'm running each test in a clean environment, on a Google Colab notebook.

1:
```
> git clone https://github.com/likyoo/open-cd.git
> cd open-cd
> pip install -v -e .
> python3 tools/train.py configs/changer/changer_ex_r18_512x512_40k_levircd.py --work-dir ./changer_r18_levir_workdir --gpu-id 0 --seed 307
Traceback (most recent call last):
File "/content/tools/train.py", line 10, in <module> import mmcv
ModuleNotFoundError: No module named 'mmcv'
```

2:
```
> git clone https://github.com/likyoo/open-cd.git
> cd open-cd
> pip install -v -e .
> cat /requirements/mminstall.txt
mmcls>=0.20.1
mmcv-full>=1.5.0,<=1.7.0

> pip install -r ./requirements/mminstall.txt
> python3 tools/train.py  configs/changer/changer_ex_r18_512x512_40k_levircd.py --work-dir ./changer_r18_levir_workdir --gpu-id 0 --seed 307
AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc4.
```

3:
```
> git clone https://github.com/likyoo/open-cd.git
> cd open-cd
> pip install -v -e .
> pip install mmcv==2.0.0rc4
> python3 tools/train.py  configs/changer/changer_ex_r18_512x512_40k_levircd.py --work-dir ./changer_r18_levir_workdir --gpu-id 0 --seed 307
Traceback (most recent call last):
File "/content/tools/train.py", line 13, in <module> from mmcv.cnn.utils import revert_sync_batchnorm
ImportError: cannot import name 'revert_sync_batchnorm' from 'mmcv.cnn.utils' (/usr/local/lib/python3.9/dist-packages/mmcv/cnn/utils/__init__.py)
```

4:
```
> git clone https://github.com/likyoo/open-cd.git
> cd open-cd
> pip install -v -e .
> pip install mmcv
> python3 tools/train.py  configs/changer/changer_ex_r18_512x512_40k_levircd.py --work-dir ./changer_r18_levir_workdir --gpu-id 0 --seed 307
Traceback (most recent call last):
File "/content/tools/train.py", line 13, in <module> from mmcv.cnn.utils import revert_sync_batchnorm
ImportError: cannot import name 'revert_sync_batchnorm' from 'mmcv.cnn.utils' (/usr/local/lib/python3.9/dist-packages/mmcv/cnn/utils/__init__.py)
```

I would appreciate any help!

Greetings!

**Comment by AgustinNormand** [comment]
I forgot to look at the reference to [open-mmlab/mmsegmentation](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/get_started.md#installation).
I will try to solve it using the documentation of that repository!
Sorry
