### ISSUE TITLE
'LEVIR_CD_Dataset' is not in the dataset registry

### ISSUE THREAD

**Issue by flying318** [likyoo/open-cd#19]
When I run `tools/test.py`, there exists an error? 
```python3
2023-04-18 16:34:01,005 - mmseg - INFO - Multi-processing start method is `None`
2023-04-18 16:34:01,005 - mmseg - INFO - OpenCV num_threads is `48
Traceback (most recent call last):
  File "/home/user/open-cd/tools/test.py", line 321, in <module>
    main()
  File "/home/user/open-cd/tools/test.py", line 193, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/user/mmsegmentation/mmseg/datasets/builder.py", line 85, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/user/miniconda3/envs/opencd/lib/python3.9/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'LEVIR_CD_Dataset is not in the dataset registry'
```
I didn't change anything in `opencd/datasets/levir_cd.py`. How can I fix this error. :sob:

**Comment by likyoo** [comment]
emmm...
try `from opencd.datasets import LEVIR_CD_Dataset` in test.py ? I am not sure..

**Comment by flying318** [comment]
Thanks, it is work for me. 😊
