### ISSUE TITLE
Error running inference

### ISSUE THREAD

**Issue by arianaa30** [likyoo/open-cd#49]
I just followed the steps for Usage, but get this error when running this command. How to solve it?

> python3 tools/test.py configs/changer/changer_ex_r18_512x512_40k_levircd.py  changer_r18_levir_workdir/latest.pth --show-dir tmp_infer

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/d/Userdata/user/Downloads/open-cd/opencd/datasets/levir_cd.py", line 18, in __init__
    super().__init__(
  File "/mnt/d/Userdata/user/Downloads/open-cd/opencd/datasets/basecddataset.py", line 141, in __init__
    self.full_init()
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 296, in full_init
    self.data_list = self.load_data_list()
  File "/mnt/d/Userdata/user/Downloads/open-cd/opencd/datasets/basecddataset.py", line 269, in load_data_list
    assert sorted(list(file_list_from)) == sorted(list(file_list_to)), \
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/fileio/io.py", line 760, in list_dir_or_file
    yield from backend.list_dir_or_file(dir_path, list_dir, list_file, suffix,
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/fileio/backends/local_backend.py", line 527, in _list_dir_or_file
    for entry in os.scandir(dir_path):
FileNotFoundError: [Errno 2] No such file or directory: 'data/LEVIR-CD/test/A'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/runner/loops.py", line 410, in __init__
    super().__init__(runner, dataloader)
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1351, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
FileNotFoundError: class `LEVIR_CD_Dataset` in opencd/datasets/levir_cd.py: [Errno 2] No such file or directory: 'data/LEVIR-CD/test/A'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/Userdata/user/Downloads/open-cd/tools/test.py", line 114, in <module>
    main()
  File "/mnt/d/Userdata/user/Downloads/open-cd/tools/test.py", line 110, in main
    runner.test()
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1774, in test
    self._test_loop = self.build_test_loop(self._test_loop)  # type: ignore
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1577, in build_test_loop
    loop = LOOPS.build(
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/user/.local/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
FileNotFoundError: class `TestLoop` in mmengine/runner/loops.py: class `LEVIR_CD_Dataset` in opencd/datasets/levir_cd.py: [Errno 2] No such file or directory: 'data/LEVIR-CD/test/A'
```

**Comment by arianaa30** [comment]
Solution: We have to download training data as the models are running on training/test data. They need to go under `/data` folder.
