### ISSUE TITLE
Error using 4-band images

### ISSUE THREAD

**Issue by AgustinNormand** [likyoo/open-cd#53]
Hello!

I'm trying to train the models with a dataset that has 4 bands: Red, Green, Blue, Near-Infrared.

I've tried a .tiff file format and also a .png format. The training in both cases seems to work, the validation iterations return reasonable metrics. So I assume that the .pth file is completely valid, the error I get is when executing the test, it cannot draw the mask resulting from the prediction.

[Tiff format training and testing notebook](https://drive.google.com/file/d/1qXbdy5Jbnd7Ah3-qI_HhIeYFG6b9RN2R/view?usp=sharing)
[Png format training and testing notebook](https://drive.google.com/file/d/1inKQ6ws5bcawq82OegbQjXfUWRlHr-tI/view?usp=sharing)

The error I get is
```
Traceback (most recent call last):
  File "/content/open-cd/tools/test.py", line 114, in <module>
    main()
  File "/content/open-cd/tools/test.py", line 110, in main
    runner.test()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1791, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/loops.py", line 435, in run
    self.run_iter(idx, data_batch)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/loops.py", line 456, in run_iter
    self.runner.call_hook(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1807, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/hooks/hook.py", line 277, in after_test_iter
    self._after_iter(
  File "/content/open-cd/opencd/engine/hooks/visualization_hook.py", line 106, in _after_iter
    self._visualizer.add_datasample(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/dist/utils.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "/content/open-cd/opencd/visualization/cd_local_visualizer.py", line 112, in add_datasample
    pred_img_data = self._draw_sem_seg(pred_img_data,
  File "/usr/local/lib/python3.10/dist-packages/mmseg/visualization/local_visualizer.py", line 115, in _draw_sem_seg
    self.draw_binary_masks(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/dist/utils.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/visualization/visualizer.py", line 894, in draw_binary_masks
    assert len(color) == 3
AssertionError
```

Thank you very much in advance

**Comment by NicolasLeoneti** [comment]
Hello, I am having the same problem, I am interested in the solution!

Thanks

**Comment by likyoo** [comment]
Could you provide the config file in your work_dir? And [this](https://github.com/open-mmlab/mmengine/blob/main/mmengine/visualization/visualizer.py#L864) may be helpful for you.

**Comment by AgustinNormand** [comment]
Hello, thank you very much for the answer, here is the [link](https://drive.google.com/drive/folders/1qKAwX-dm-dkD79SQ6c_yMxyqkNFNw1iH?usp=sharing) to the folder where I store the files related to the notebook.

I'll check that link you sent me, thanks!

**Comment by likyoo** [comment]
![image](https://github.com/likyoo/open-cd/assets/44317497/53c25035-4091-4ee7-bebd-7f431082211b)

Try:
```
palette=[[0, 0, 0], [255, 255, 255]]
```

**Comment by AgustinNormand** [comment]
I did a quick workout, just a couple of iterations, and it seems to have worked.

I am going to run a training with several iterations, and verify that the model is working correctly, generating the predictions of the labels, and so on.
I'll confirm this tomorrow, and I'll close the issue if there aren't any errors.
Thank you so much!

**Comment by AgustinNormand** [comment]
The question that arises to me is, using that palette of length 3, which I understand refers to the RGB bands, wouldn't it be making the model train ignoring the fourth band?

**Comment by NicolasLeoneti** [comment]
> The question that arises to me is, using that palette of length 3, which I understand refers to the RGB bands, wouldn't it be making the model train ignoring the fourth band?

It worked for me too, but that's a good question.

**Comment by AgustinNormand** [comment]
> The question that arises to me is, using that palette of length 3, which I understand refers to the RGB bands, wouldn't it be making the model train ignoring the fourth band?

Hello

I ran a full training with the 4-band dataset, and there is no performance difference from the 3-band dataset.

Which makes me think that maybe you are ignoring said 4th rail, otherwise the performance should be modified even a bit.

Could it be that I'm ignoring the fourth band? Or the palette has nothing to do with it?

**Comment by likyoo** [comment]
emmm.. I think the palette is just for visualization.
plz make sure all bands are loaded. Check [here](https://github.com/likyoo/open-cd/blob/main/opencd/models/backbones/tinynet.py#L415), [here](https://github.com/likyoo/open-cd/blob/main/configs/_base_/models/tinycd_v2.py#L5), [here](https://github.com/likyoo/open-cd/blob/main/configs/_base_/models/tinycd_v2.py#L7), and so on.

**Comment by AgustinNormand** [comment]
You're right, I have to modify the models to specify that they should read the 4 bands,

If I manage to make it work, I'll put a link to the Colab notebook in case it helps someone else

Thank you

**Comment by NicolasLeoneti** [comment]
And what do I specify in the array of [mean](https://github.com/likyoo/open-cd/blob/main/configs/_base_/models/tinycd_v2.py#L5) and [std](https://github.com/likyoo/open-cd/blob/main/configs/_base_/models/tinycd_v2.py#L6)? Where do those values come from?

**Comment by AgustinNormand** [comment]
Hello, I am not able to find the part of the code that is reading the files only with 3 bands, avoiding the reading of the fourth one. Where do you read the images? Is it hardcoded that only 3 bands are read?

I noticed this because of the following:
I modified several files, I added a made-up value in the [mean](https://github.com/AgustinNormand/open-cd/blob/a86f8f19fd7a129f9bcfacf62e1a64432406dc2b/configs/_base_/models/tinycd.py#L5) array ([because I don't know where it comes from either](https://github.com/likyoo/open-cd/issues/53#issuecomment-1676104664)), also in the [std](https://github.com/AgustinNormand/open-cd/blob/a86f8f19fd7a129f9bcfacf62e1a64432406dc2b/configs/_base_/models/tinycd.py#L6) array, and I set the [bgr_to_rgb](https://github.com/AgustinNormand/open-cd/blob/a86f8f19fd7a129f9bcfacf62e1a64432406dc2b/configs/_base_/models/tinycd.py#L7) flag to false.
I changed the [input](https://github.com/AgustinNormand/open-cd/blob/a86f8f19fd7a129f9bcfacf62e1a64432406dc2b/opencd/models/backbones/tinynet.py#L415) channels of the tinynet convolution.

I added a [print](https://github.com/AgustinNormand/open-cd/blob/a86f8f19fd7a129f9bcfacf62e1a64432406dc2b/opencd/models/data_preprocessor.py#L221) before the error to see the shape, and it is torch.Size([6, 256, 256])
