### ISSUE TITLE
'MultiImgLoadImageFromFile is not in the transform registry.

### ISSUE THREAD

**Issue by work1-shekhaman** [likyoo/open-cd#67]
(openmmlab) trest@~/open-cd$ python tools/train.py configs/changeformer/changeformer_mit-b0_256x256_40k_levircd.py --work-dir work-dirs/temp/
10/20 14:03:38 - mmengine - INFO -
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 537977676
    GPU 0: Tesla V100-SXM2-16GB
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.3, V11.3.109
    GCC: gcc (Debian 8.3.0-6) 8.3.0
    PyTorch: 1.12.0+cu113
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
    - Built with CuDNN 8.3.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

    TorchVision: 0.13.0+cu113
    OpenCV: 4.8.1
    MMEngine: 0.6.0

Runtime environment:
    cudnn_benchmark: True
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

10/20 14:03:39 - mmengine - INFO - Config:
norm_cfg = dict(type='SyncBN', requires_grad=True)
data_preprocessor = dict(
    type='DualInputSegDataPreProcessor',
    mean=[123.675, 116.28, 103.53, 123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375, 58.395, 57.12, 57.375],
    bgr_to_rgb=True,
    size_divisor=32,
    pad_val=0,
    seg_pad_val=255,
    test_cfg=dict(size_divisor=32))
model = dict(
    type='SiamEncoderDecoder',
    data_preprocessor=dict(
        type='DualInputSegDataPreProcessor',
        mean=[123.675, 116.28, 103.53, 123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375, 58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        size_divisor=32,
        pad_val=0,
        seg_pad_val=255,
        test_cfg=dict(size_divisor=32)),
    pretrained=
    'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segformer/mit_b0_20220624-7e0fe6dd.pth',
    backbone=dict(
        type='mmseg.MixVisionTransformer',
        in_channels=3,
        embed_dims=32,
        num_stages=4,
        num_layers=[2, 2, 2, 2],
        num_heads=[1, 2, 5, 8],
        patch_sizes=[7, 3, 3, 3],
        sr_ratios=[8, 4, 2, 1],
        out_indices=(0, 1, 2, 3),
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.1),
    neck=dict(type='FeatureFusionNeck', policy='concat'),
    decode_head=dict(
        type='mmseg.SegformerHead',
        in_channels=[64, 128, 320, 512],
        in_index=[0, 1, 2, 3],
        channels=256,
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='mmseg.CrossEntropyLoss', use_sigmoid=False,
            loss_weight=1.0)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
default_scope = 'opencd'
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='CDLocalVisBackend')]
visualizer = dict(
    type='CDLocalVisualizer',
    vis_backends=[dict(type='CDLocalVisBackend')],
    name='visualizer',
    alpha=1.0)
log_processor = dict(by_epoch=False)
log_level = 'INFO'
load_from = None
resume = False
tta_model = dict(type='mmseg.SegTTAModel')
dataset_type = 'LEVIR_CD_Dataset'
data_root = 'data/levir'
crop_size = (256, 256)
train_pipeline = [
    dict(type='MultiImgLoadImageFromFile'),
    dict(type='MultiImgLoadAnnotations'),
    dict(type='MultiImgRandomRotate', prob=0.5, degree=180),
    dict(type='MultiImgRandomCrop', crop_size=(256, 256), cat_max_ratio=0.75),
    dict(type='MultiImgRandomFlip', prob=0.5, direction='horizontal'),
    dict(type='MultiImgRandomFlip', prob=0.5, direction='vertical'),
    dict(
        type='MultiImgPhotoMetricDistortion',
        brightness_delta=10,
        contrast_range=(0.8, 1.2),
        saturation_range=(0.8, 1.2),
        hue_delta=10),
    dict(type='MultiImgPackSegInputs')
]
test_pipeline = [
    dict(type='MultiImgLoadImageFromFile'),
    dict(type='MultiImgResize', scale=(1024, 1024), keep_ratio=True),
    dict(type='MultiImgLoadAnnotations'),
    dict(type='MultiImgPackSegInputs')
]
img_ratios = [0.75, 1.0, 1.25]
tta_pipeline = [
    dict(type='MultiImgLoadImageFromFile', backend_args=None),
    dict(
        type='TestTimeAug',
        transforms=[[{
            'type': 'MultiImgResize',
            'scale_factor': 0.75,
            'keep_ratio': True
        }, {
            'type': 'MultiImgResize',
            'scale_factor': 1.0,
            'keep_ratio': True
        }, {
            'type': 'MultiImgResize',
            'scale_factor': 1.25,
            'keep_ratio': True
        }],
                    [{
                        'type': 'MultiImgRandomFlip',
                        'prob': 0.0,
                        'direction': 'horizontal'
                    }, {
                        'type': 'MultiImgRandomFlip',
                        'prob': 1.0,
                        'direction': 'horizontal'
                    }], [{
                        'type': 'MultiImgLoadAnnotations'
                    }], [{
                        'type': 'MultiImgPackSegInputs'
                    }]])
]
train_dataloader = dict(
    batch_size=8,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type='LEVIR_CD_Dataset',
        data_root='data/levir',
        data_prefix=dict(
            seg_map_path='train/label',
            img_path_from='train/A',
            img_path_to='train/B'),
        pipeline=[
            dict(type='MultiImgLoadImageFromFile'),
            dict(type='MultiImgLoadAnnotations'),
            dict(type='MultiImgRandomRotate', prob=0.5, degree=180),
            dict(
                type='MultiImgRandomCrop',
                crop_size=(256, 256),
                cat_max_ratio=0.75),
            dict(type='MultiImgRandomFlip', prob=0.5, direction='horizontal'),
            dict(type='MultiImgRandomFlip', prob=0.5, direction='vertical'),
            dict(
                type='MultiImgPhotoMetricDistortion',
                brightness_delta=10,
                contrast_range=(0.8, 1.2),
                saturation_range=(0.8, 1.2),
                hue_delta=10),
            dict(type='MultiImgPackSegInputs')
        ]))
val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='LEVIR_CD_Dataset',
        data_root='data/levir',
        data_prefix=dict(
            seg_map_path='val/label',
            img_path_from='val/A',
            img_path_to='val/B'),
        pipeline=[
            dict(type='MultiImgLoadImageFromFile'),
            dict(type='MultiImgResize', scale=(1024, 1024), keep_ratio=True),
            dict(type='MultiImgLoadAnnotations'),
            dict(type='MultiImgPackSegInputs')
        ]))
test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='LEVIR_CD_Dataset',
        data_root='data/levir',
        data_prefix=dict(
            seg_map_path='test/label',
            img_path_from='test/A',
            img_path_to='test/B'),
        pipeline=[
            dict(type='MultiImgLoadImageFromFile'),
            dict(type='MultiImgResize', scale=(1024, 1024), keep_ratio=True),
            dict(type='MultiImgLoadAnnotations'),
            dict(type='MultiImgPackSegInputs')
        ]))
val_evaluator = dict(type='mmseg.IoUMetric', iou_metrics=['mFscore', 'mIoU'])
test_evaluator = dict(type='mmseg.IoUMetric', iou_metrics=['mFscore', 'mIoU'])
optimizer = dict(type='AdamW', lr=6e-05, betas=(0.9, 0.999), weight_decay=0.01)
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='AdamW', lr=6e-05, betas=(0.9, 0.999), weight_decay=0.01),
    paramwise_cfg=dict(
        custom_keys=dict(
            pos_block=dict(decay_mult=0.0),
            norm=dict(decay_mult=0.0),
            head=dict(lr_mult=10.0))))
param_scheduler = [
    dict(
        type='LinearLR', start_factor=1e-06, by_epoch=False, begin=0,
        end=1000),
    dict(
        type='PolyLR',
        power=1.0,
        begin=1000,
        end=40000,
        eta_min=0.0,
        by_epoch=False)
]
train_cfg = dict(type='IterBasedTrainLoop', max_iters=40000, val_interval=4000)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50, log_metric_by_epoch=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(
        type='CheckpointHook', by_epoch=False, interval=4000,
        save_best='mIoU'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(
        type='CDVisualizationHook', interval=1, img_shape=(1024, 1024, 3)))
checkpoint = 'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segformer/mit_b0_20220624-7e0fe6dd.pth'
launcher = 'none'
work_dir = 'work-dirs/temp/'

/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmseg/models/backbones/mit.py:365: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmseg/models/decode_heads/decode_head.py:120: UserWarning: For binary segmentation, we suggest using`out_channels = 1` to define the outputchannels of segmentor, and use `threshold`to convert `seg_logits` into a predictionapplying a threshold
  warnings.warn('For binary segmentation, we suggest using'
/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmseg/models/builder.py:36: UserWarning: ``build_loss`` would be deprecated soon, please use ``mmseg.registry.MODELS.build()``
  warnings.warn('``build_loss`` would be deprecated soon, please use '
/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
10/20 14:03:43 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
/home/aman/elm/open-cd/opencd/engine/hooks/visualization_hook.py:59: UserWarning: The draw is False, it means that the hook for visualization will not take effect. The results will NOT be visualized or stored.
  warnings.warn('The draw is False, it means that the '
10/20 14:03:43 - mmengine - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) RuntimeInfoHook
(BELOW_NORMAL) LoggerHook
 --------------------
before_train:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(VERY_LOW    ) CheckpointHook
 --------------------
before_train_epoch:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(NORMAL      ) DistSamplerSeedHook
 --------------------
before_train_iter:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
 --------------------
after_train_iter:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(NORMAL      ) CDVisualizationHook
(BELOW_NORMAL) LoggerHook
(LOW         ) ParamSchedulerHook
(VERY_LOW    ) CheckpointHook
 --------------------
after_train_epoch:
(NORMAL      ) IterTimerHook
(LOW         ) ParamSchedulerHook
(VERY_LOW    ) CheckpointHook
 --------------------
before_val_epoch:
(NORMAL      ) IterTimerHook
 --------------------
before_val_iter:
(NORMAL      ) IterTimerHook
 --------------------
after_val_iter:
(NORMAL      ) IterTimerHook
(NORMAL      ) CDVisualizationHook
(BELOW_NORMAL) LoggerHook
 --------------------
after_val_epoch:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(BELOW_NORMAL) LoggerHook
(LOW         ) ParamSchedulerHook
(VERY_LOW    ) CheckpointHook
 --------------------
before_test_epoch:
(NORMAL      ) IterTimerHook
 --------------------
before_test_iter:
(NORMAL      ) IterTimerHook
 --------------------
after_test_iter:
(NORMAL      ) IterTimerHook
(NORMAL      ) CDVisualizationHook
(BELOW_NORMAL) LoggerHook
 --------------------
after_test_epoch:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(BELOW_NORMAL) LoggerHook
 --------------------
after_run:
(BELOW_NORMAL) LoggerHook
 --------------------
10/20 14:03:44 - mmengine - WARNING - Failed to import opencd.datasets, please check the location of the registry dataset is correct.
10/20 14:03:44 - mmengine - WARNING - Failed to import opencd.datasets.transforms, please check the location of the registry transform is correct.
Traceback (most recent call last):
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/aman/elm/open-cd/opencd/datasets/levir_cd.py", line 18, in __init__
    super().__init__(
  File "/home/aman/elm/open-cd/opencd/datasets/basecddataset.py", line 138, in __init__
    self.pipeline = Compose(pipeline)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 36, in __init__
    transform = TRANSFORMS.build(transform)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'MultiImgLoadImageFromFile is not in the transform registry. Please check whether the value of `MultiImgLoadImageFromFile` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 210, in __init__
    super().__init__(runner, dataloader)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1333, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: "class `LEVIR_CD_Dataset` in opencd/datasets/levir_cd.py: 'MultiImgLoadImageFromFile is not in the transform registry. Please check whether the value of `MultiImgLoadImageFromFile` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 100, in main
    runner.train()
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1656, in train
    self._train_loop = self.build_train_loop(
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1448, in build_train_loop
    loop = LOOPS.build(
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: 'class `IterBasedTrainLoop` in mmengine/runner/loops.py: "class `LEVIR_CD_Dataset` in opencd/datasets/levir_cd.py: \'MultiImgLoadImageFromFile is not in the transform registry. Please check whether the value of `MultiImgLoadImageFromFile` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module\'"'

**Comment by likyoo** [comment]
try `pip install -e .`

**Comment by work1-shekhaman** [comment]
thanks for helping i needed to change the version of some libraries its working fine, but there is one more issue I am facing. 

1.  In my data/sysu/test folder images (in A/ and B/) are of shape (256,256,3) and labels (label/) are of shape (256,256).

I am not able to get prediction of images when using python tools/test.py command with --show-dir argument, evaluation part is working good by using same command without --show-dir argument. below is snippet of error i am getting 


Loads checkpoint by local backend from path: work-dirs/train/changeformer/mit_b1_256_75k_b16_clr_sysu/iter_10000.pth
10/21 11:08:33 - mmengine - INFO - Load checkpoint from work-dirs/train/changeformer/mit_b1_256_75k_b16_clr_sysu/iter_10000.pth
Traceback (most recent call last):
  File "tools/test.py", line 114, in <module>
    main()
  File "tools/test.py", line 110, in main
    runner.test()
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1823, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 435, in run
    self.run_iter(idx, data_batch)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 456, in run_iter
    self.runner.call_hook(
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1839, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/hooks/hook.py", line 277, in after_test_iter
    self._after_iter(
  File "/home/aman/elm/open-cd/opencd/engine/hooks/visualization_hook.py", line 106, in _after_iter
    self._visualizer.add_datasample(
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dist/utils.py", line 412, in wrapper
    return func(*args, **kwargs)
  File "/home/aman/elm/open-cd/opencd/visualization/cd_local_visualizer.py", line 112, in add_datasample
    pred_img_data = self._draw_sem_seg(pred_img_data,
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmseg/visualization/local_visualizer.py", line 115, in _draw_sem_seg
    self.draw_binary_masks(
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dist/utils.py", line 412, in wrapper
    return func(*args, **kwargs)
  File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/visualization/visualizer.py", line 881, in draw_binary_masks
    assert img.shape[:2] == binary_masks.shape[
AssertionError: `binary_marks` must have the same shape with image

**Comment by work1-shekhaman** [comment]
> thanks for helping i needed to change the version of some libraries its working fine, but there is one more issue I am facing.
> 
> 1. In my data/sysu/test folder images (in A/ and B/) are of shape (256,256,3) and labels (label/) are of shape (256,256).
> 
> I am not able to get prediction of images when using python tools/test.py command with --show-dir argument, evaluation part is working good by using same command without --show-dir argument. below is snippet of error i am getting
> 
> Loads checkpoint by local backend from path: work-dirs/train/changeformer/mit_b1_256_75k_b16_clr_sysu/iter_10000.pth 10/21 11:08:33 - mmengine - INFO - Load checkpoint from work-dirs/train/changeformer/mit_b1_256_75k_b16_clr_sysu/iter_10000.pth Traceback (most recent call last): File "tools/test.py", line 114, in main() File "tools/test.py", line 110, in main runner.test() File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1823, in test metrics = self.test_loop.run() # type: ignore File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 435, in run self.run_iter(idx, data_batch) File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 456, in run_iter self.runner.call_hook( File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1839, in call_hook getattr(hook, fn_name)(self, **kwargs) File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/hooks/hook.py", line 277, in after_test_iter self._after_iter( File "/home/aman/elm/open-cd/opencd/engine/hooks/visualization_hook.py", line 106, in _after_iter self._visualizer.add_datasample( File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dist/utils.py", line 412, in wrapper return func(*args, **kwargs) File "/home/aman/elm/open-cd/opencd/visualization/cd_local_visualizer.py", line 112, in add_datasample pred_img_data = self._draw_sem_seg(pred_img_data, File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmseg/visualization/local_visualizer.py", line 115, in _draw_sem_seg self.draw_binary_masks( File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dist/utils.py", line 412, in wrapper return func(*args, **kwargs) File "/home/aman/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/visualization/visualizer.py", line 881, in draw_binary_masks assert img.shape[:2] == binary_masks.shape[ AssertionError: `binary_marks` must have the same shape with image

I have also tried to convert my test/label/ images to shape (256,256,3), but still getting same error
