### ISSUE TITLE
Fail to install when following instruction on README.md

### ISSUE THREAD

**Issue by chilin0525** [likyoo/open-cd#68]
* OS: Ubuntu 20.04
* Python: 3.8
* After install in new virtual environment, got error message:
```
❯ python3
Python 3.8.0 (default, Apr 23 2023, 05:48:37)
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from opencd.apis import OpenCDInferencer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chilin/open-cd/opencd/apis/__init__.py", line 2, in <module>
    from .opencd_inferencer import OpenCDInferencer
  File "/home/chilin/open-cd/opencd/apis/opencd_inferencer.py", line 11, in <module>
    from mmseg.utils import ConfigType
  File "/home/chilin/mmsegmentation/mmseg/utils/__init__.py", line 24, in <module>
    from .mask_classification import MatchMasks, seg_data_to_instance_data
  File "/home/chilin/mmsegmentation/mmseg/utils/mask_classification.py", line 5, in <module>
    from mmcv.ops import point_sample
  File "/home/chilin/.pyenv/versions/3.8.0/envs/test_opencd/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/chilin/.pyenv/versions/3.8.0/envs/test_opencd/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/chilin/.pyenv/versions/3.8.0/envs/test_opencd/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/chilin/.pyenv/versions/3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
>>> exit()
```

**Comment by chilin0525** [comment]
Downgrade torch version and reinstall work for me.
Close the issue.

**Comment by hamzagorgulu** [comment]
Hi, which version did you downgraded to?
